### PR TITLE
Improvements for `GhostBox`

### PR DESCRIPTION
**Pull request by arnaudgolfouse**

### CODE REVIEW

**Comment by arnaudgolfouse** [comment]
@xldenis I added a hack to dereference a `GhostBox` in pearlite, does it look reasonable?

**Comment by xldenis** [comment]
Yea, its definitely a hack but far from the worst we've had. Do you expect to add other similar cases?

**Comment by arnaudgolfouse** [comment]
Not really. If more cases are ever needed I'd rather find a more general solution.

**Comment by arnaudgolfouse** [comment]
If the question is "will you add this for `Seq` and `Map`" the answer is not 🙂

**Review by xldenis — APPROVED** [review]

**Pull request merged**
