### PR TITLE
Stabilize list_reversal_lasso.

### PR DESCRIPTION
**Pull request by jhjourdan**

### CODE REVIEW

**Comment by jhjourdan** [comment]
There is really a big difference between the timing I can observe on my machine and those seen on CI. Is this related to the problem we have with reproducibility of step counts?

**Comment by xldenis** [comment]
Not sure what you mean?

**Comment by jhjourdan** [comment]
I mean that clearly the SMT solvers do not have the same behavior depending on the machine, and apparently this is true for both Altergo and CVC5. Hence this is indicating that Why3 non-deterministically generate different SMT files, depending on something from the environment. This would explain the instabilities we are observing here, and the step count problems.

**Comment by xldenis** [comment]
Interesting hypothesis. That seems like highly possible, but I will note that the steps fail locally on your machine if you try replaying a proof twice.

**Pull request merged**
