### PR TITLE
Add why3find dependency to nightly

### PR DESCRIPTION
**Pull request by Lysxia**
D:

### CODE REVIEW

**Comment by Armael** [comment]
I think you also need to fix `nightly.yml` to pass `--no-check-version` for why3find

**Comment by jhjourdan** [comment]
> I think you also need to fix `nightly.yml` to pass `--no-check-version` for why3find

Really? If the version does not match, then we need to know that, and update Why3find.

**Comment by Armael** [comment]
Well the point of the nightly job is to see whether creusot works with the newest (possibly different) version of why3find. (We already pass the same option for why3 right now.)

**Comment by jhjourdan** [comment]
I don't think the version check of why3find checks the individual commit.

**Comment by Lysxia** [comment]
Nightly went green again

**Pull request merged**
