### PR TITLE
Inherit trusted attribute from parents

### PR DESCRIPTION
**Pull request by xldenis**
Here's a rough prototype of what was proposed to solve #1067.

I need to actually add tests here, but it should cover the intended usecase.

There's a wrinkle in the form of `trusted` on traits and types also having different semantics: I don't think we want to inherit `trusted` on types from parent modules, it makes them opaque. Similarly we probably don't want to inherit `trusted` for trait declarations?

### CODE REVIEW

**Comment by jhjourdan** [comment]
Right. Note that the trusted declaration for types should go away at some point. Privacy is the right way of making types opaque.

**Comment by xldenis** [comment]
@mojeanmac can you try this branch experimentally? you should be able to put `#[trusted]` on modules to disable all vcgen on anything inside, but I'm not sure I caught every edge case.

**Comment by mojeanmac** [comment]
Ah here's one case where trusted doesn't cut it: Creusot still expects some impl'd traits to have the `creusot_contracts` definition as well. For example, a custom data type using `Default` still needs `creusot_contracts::Default` regardless if the module it's in is trusted or not.

**Comment by xldenis** [comment]
Ah yea good point. I can't think of any *great* solution, but:

1. Use `cfg_attr(creusot,...)` to conditionally disable them.
2. Put the impls in a creusot only module.

**Pull request merged**
